version: "3.7"

services:
  neo4j:
    image: neo4j
    hostname: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "./.neo4j/data:/data"
      - "./.neo4j/logs:/logs"
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_server_memory_heap_max__size: 2G
      NEO4J_server_memory_heap_initial__size: 2G
      NEO4J_server_memory_pagecache_size: 1G
      NEO4J_dbms_security_auth__minimum__password__length: 1
